services:
  spark-master:
    image: bitnami/spark:3.3
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"   # Spark master RPC
      - "8080:8080"   # Spark master UI
    volumes:
      - ./data:/data

  spark-worker:
    image: bitnami/spark:3.3
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "8081:8081"   # Spark worker UI
    volumes:
      - ./data:/data

  jupyter:
    build: ./jupyter
    container_name: spark-jupyter
    hostname: spark-jupyter
    ports:
      - "8888:8888"   # Jupyter Notebook
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/data
    environment:
      - PYSPARK_PYTHON=python
      - PYSPARK_DRIVER_PYTHON=jupyter
      - PYSPARK_DRIVER_PYTHON_OPTS=notebook --ip=0.0.0.0 --no-browser --allow-root