version: '3.8'

services:
  spark-master:
    image: bitnami/spark:3.3
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./data:/data

  spark-worker:
    image: bitnami/spark:3.3
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "8081:8081"
    volumes:
      - ./data:/data

  jupyter:
    build: ./jupyter
    container_name: spark-jupyter
    hostname: spark-jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/data
    environment:
      - PYSPARK_PYTHON=python
      - PYSPARK_DRIVER_PYTHON=jupyter
      - PYSPARK_DRIVER_PYTHON_OPTS=notebook --ip=0.0.0.0 --no-browser --allow-root

  streamlit:
    build: ./frontend
    container_name: streamlit-ui
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: streamlit run app.py --server.port=8501 --server.enableCORS=false